[server]
host = "0.0.0.0"
port = 9000

[metadata]
path = "/tmp/s3-meta"

[[directories]]
path = "/tmp/s3-data0"

[[directories]]
path = "/tmp/s3-data1"

[[auth.credentials]]
access_key = "admin"
secret_key = "password123"

[[auth.credentials]]
access_key = "test"
secret_key = "testtest"
